apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_URI: Ylc5dVoyOWtZaXR6Y25ZNkx5OXNkV2x6YjNCaGVtODZhV3h4TTBSUVdHTTFjRVJ2YUdWTWNVQmpiSFZ6ZEdWeU1DNDROWEoxYUM1dApiMjVuYjJSaUxtNWxkQzgvY21WMGNubFhjbWwwWlhNOWRISjFaU1ozUFcxaGFtOXlhWFI1Sm1Gd2NFNWhiV1U5UTJ4MWMzUmxjakE9Cg==
